title: Welcome to Pack 3943
email: 1phillip.guzman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a informational Page for Pack 3943
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:/pack3943.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Pack-3943
gems:
    - jekyll-leaflet
# Build settings
theme: minima
plugins:
  - jekyll-feed

tab_pages:
  - title: "about"
    path: about.md
    url: "/about"
